services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: maintu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: gunicorn maintu.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"  # host:container
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: npm start
    ports:
      - "3000:3000"  # host:container
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    depends_on:
      - backend
volumes:
  postgres_data:
