# Generated by Django 4.2.7 on 2025-07-23 06:24

from django.db import migrations, models
import django.utils.timezone
import parts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedCSV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=parts.models.upload_to)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("original_name", models.CharField(max_length=255)),
            ],
        ),
    ]
